apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashupservice-deployment
  labels:
    app: cashupservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cashupservice
  template:
    metadata:
      labels:
        app: cashupservice

    spec:
      containers:
        - name: cashupservice
          image: akki1999/cashupservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: cashupservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: cashupservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cashupservice-secrets
                  key: cashupservicepi-key