apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypalservice-deployment
  labels:
    app: paypalservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paypalservice
  template:
    metadata:
      labels:
        app: paypalservice

    spec:
      containers:
        - name: paypalservice
          image: akki1999/paypalservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: paypalservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paypalservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: paypalservice-secrets
                  key: paypalservicepi-key