apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditservice-deployment
  labels:
    app: creditservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: creditservice
  template:
    metadata:
      labels:
        app: creditservice

    spec:
      containers:
        - name: creditservice
          image: akki1999/creditservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: creditservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: creditservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: creditservice-secrets
                  key: creditservicepi-key